

services:
  # Multi-Bunker Server
  bunker-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: openbunker-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NOSTR_RELAYS=wss://relay.nsec.app
      # Add other environment variables as needed
    volumes:
      - ./prisma:/app/prisma
    env_file:
      - .env.local
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "true"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Next.js Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openbunker-frontend
    restart: unless-stopped
    depends_on:
      bunker-server:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BUNKER_SERVER_URL=http://bunker-server:3001
      # Add other environment variables as needed
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3


networks:
  default:
    name: openbunker-network
